### ISSUE TITLE
MACHINE=ok6254c-k3r5-hs-fs is invalid.

### ISSUE THREAD

**Issue by jesses2025smith** [UWINGS-KUNYI/meta-ok6254c#1]
![image](https://user-images.githubusercontent.com/15953541/233819540-a6bb9d04-d6ea-469e-9445-3d7998f67f02.png)

HOST: ubuntu20.04 LTS
Kernel: 5.15.0-69

**Comment by KunYi** [comment]
if you want use HS version you need to create new machine conf

currently only support 'ok6254c' 
![image](https://user-images.githubusercontent.com/2186922/233826853-10852a28-7694-4ee1-9199-21ea208612af.png)
